---
- name: Create application user
  user: name={{ symfony_release_user }}

- name: Create release dir
  file: 
    path: "/home/{{ symfony_release_user }}/{{ symfony_release_project }}/releases"
    state: directory
    mode: 0755
    owner: "{{ symfony_release_user }}"

- name: Deploying application code
  unarchive:
    src: "{{ symfony_release_path }}"
    dest: "/home/{{ symfony_release_user }}/{{ symfony_release_project }}/releases/"
    creates: "/home/{{ symfony_release_user }}/{{ symfony_release_project }}/releases/{{ symfony_release_name }}"
    copy: yes
    mode: 0755
    owner: "{{ symfony_release_user }}"

- name: Set correct permissions
  file:
    path: "/home/{{ symfony_release_user }}/{{ symfony_release_project }}/releases/{{ symfony_release_name }}"
    # mode: 0755
    owner: "{{ symfony_release_user }}"
    state: directory
    recurse: true

- name: Link current release
  file:
    src: "/home/{{ symfony_release_user }}/{{ symfony_release_project }}/releases/{{ symfony_release_name }}"
    dest: "/home/{{ symfony_release_user }}/{{ symfony_release_project }}/releases/current"
    owner: "{{ symfony_release_user }}"
    state: link
