---
- name: Pull sources from the repository.
  git:
    repo: "{{ symfony_build_repo }}"
    dest: "{{ symfony_build_dir }}"
    version: "{{ symfony_build_branch }}"
  notify:
    - create archive

- name: Run bower install
  command: >
    bower install --production --silent
  args:
    chdir: "{{ symfony_build_dir }}"
    creates: "{{ symfony_build_dir }}/src/Hobby/Bundle/BaseBundle/Resources/public/vendor"
  notify:
    - create archive

- name: Install composer
  get_url: 
    url: https://getcomposer.org/composer.phar
    dest: "{{ symfony_build_dir }}/composer.phar"
    mode: 0755
    validate_certs: no
  notify:
    - create archive

- name: Run composer install
  command: >
    ./composer.phar install 
    --no-dev  --ignore-platform-reqs --no-interaction
    --prefer-dist --optimize-autoloader --quiet
  args:
    chdir: "{{ symfony_build_dir }}"
    creates: "{{ symfony_build_dir }}/vendor"
  environment:
    SYMFONY_ENV: prod
  notify:
    - create archive

- name: get cache dirs
  shell: "ls -1 {{ symfony_build_dir }}/app/cache"
  register: cache

- name: Remove cache
  file:
    name: "{{ symfony_build_dir }}/app/cache/{{ item }}"
    state: absent
  with_items: cache.stdout_lines
  notify:
    - create archive

- name: configuration
  template:
    src: "{{ symfony_build_paramters_path }}"
    dest: "{{ symfony_build_dir }}/app/config/parameters.yml"
    mode: 0600
  notify:
    - create archive

- name: set archive path
  set_fact:
    symfony_build_archive_path: "{{ symfony_build_dir }}/../{{ symfony_build_name }}.tar.bz2"

- name: Dump build archive path
  debug: var=symfony_build_archive_path
