---
- name: Add Elasticsearch apt signing key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch id=D88E42B4 state=present

- name: Add Elasticsearch repository
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_version }}/debian stable main'
    state: present

- name: Install Elasticsearch packages
  apt: update_cache=yes pkg={{ item }} state=present
  with_items:
    - default-jre-headless
    - elasticsearch

- name: Start and enable Elasticsearch
  service: name=elasticsearch state=started enabled=yes
