---
- name: php5 is installed
  apt: pkg={{ item }} state=installed
  with_items:
   - php5-fpm
   - php5-cli 
   - php5-apcu
   - php5-mysql
   - php5-intl
   - php5-curl
   - php5-imagick
  notify:
    - restart php-fpm

- name: timezone is set
  ini_file: dest={{ item }} section=PHP option=date.timezone value=Europe/Sofia
  with_items:
   - /etc/php5/fpm/php.ini
   - /etc/php5/cli/php.ini
  notify:
    - restart php-fpm

- name: ext-zmq requirements are installed
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-dev
    - php-pear
    - libzmq-dev
    - pkg-config

- name: ext-zmq is installed
  shell: echo "\n" | pecl install -Z zmq-beta
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  notify:
    - restart php-fpm

- name: zmq.ini exists
  ini_file: dest=/etc/php5/mods-available/zmq.ini section=PHP option=extension value=zmq.so mode=0644
  notify:
    - restart php-fpm

- name: zmq module is enabled
  command: php5enmod zmq creates=/etc/php5/fpm/conf.d/20-zmq.ini
  notify:
    - restart php-fpm

- name: php5-fpm is running
  service: name=php5-fpm state=started enabled=yes
